/*
 * ============================================================================
 *  VINHO 24 HORAS — Base de dados dos vinhos (BACKUP / fallback)
 * ============================================================================
 *
 *  ATENÇÃO: a fonte de dados AO VIVO é o Google Sheets (ver SHEET_CSV_URL em
 *  app.js). Este arquivo é só o "plano B": se a planilha ficar fora do ar, o
 *  app usa os vinhos abaixo. Para mudar o que o cliente vê no dia a dia, edite
 *  a PLANILHA, não este arquivo. Mantemos os dois iguais quando fazemos uma
 *  atualização grande (como esta, com o estoque real da Unidade Ecopark IV).
 *
 *  Cada objeto abaixo é UMA LINHA da planilha. As chaves são as COLUNAS.
 *
 *  ESCALAS (de 0 a 5):
 *    docura   0 = bem seco   ......... 5 = bem doce
 *    corpo    0 = leve/fácil ......... 5 = encorpado/potente
 *    taninos  0 = macio      ......... 5 = marcante ("amarra a boca")
 *    acidez   0 = baixa      ......... 5 = alta/refrescante
 *
 *  codigo : código do vinho no sistema de estoque (para conferência).
 *  gelavel: true = fica ótimo BEM GELADO (bom argumento no clima tropical).
 *  foto   : link de uma imagem; vazio = garrafa ilustrada automática.
 * ============================================================================
 */

// As adegas. O QR de cada porta aponta para ?adega=<slug>
//
// "ativa: false" ESCONDE a unidade da tela de seleção e do gerador de QR
// (para clientes não verem uma unidade que ainda não abriu). Quando a 2ª
// unidade inaugurar, basta trocar para "ativa: true".
const ADEGAS = {
  "ecopark-iv": {
    nome: "Vinho 24 Horas · Unidade Ecopark IV",
    cidade: "Ecopark IV",
    ativa: true,
  },
  "j-prime-santa-ines": {
    nome: "Vinho 24 Horas · J. Prime",
    cidade: "Bairro Santa Inês",
    ativa: false, // reabilitar quando a 2ª unidade inaugurar
  },
};

const VINHOS = [
  {
    id: "por-mi-vieja",
    codigo: "7798370260676",
    foto: "fotos/por-mi-vieja.png",
    adegas: ["ecopark-iv"],
    nome: "Por Mi Vieja",
    produtor: "Salvador Patti",
    tipo: "Tinto",
    uva: "Malbec",
    pais: "Argentina",
    regiao: "Luján de Cuyo",
    safra: "—",
    alcool: 13.5,
    docura: 1, corpo: 4, taninos: 3, acidez: 2,
    gelavel: false,
    temperatura: "16–18 °C",
    harmonizacao: "Churrasco, carnes vermelhas, hambúrguer, massas encorpadas.",
    queijos: "Queijos curados: parmesão, gouda envelhecido.",
    descricao: "Malbec argentino encorpado e frutado (ameixa, amora), macio e cheio de sabor. O tinto coringa para acompanhar carne.",
    combina_se_voce_gosta: "de tinto encorpado para acompanhar carne.",
  },
  {
    id: "crotta-malbec-reserva",
    codigo: "1063",
    foto: "fotos/crotta-malbec-reserva.jpg",
    adegas: ["ecopark-iv"],
    nome: "Crotta Malbec Reserva",
    produtor: "Familia Crotta",
    tipo: "Tinto",
    uva: "Malbec",
    pais: "Argentina",
    regiao: "Mendoza",
    safra: "—",
    alcool: 14,
    docura: 0, corpo: 4, taninos: 4, acidez: 2,
    gelavel: false,
    temperatura: "16–18 °C",
    harmonizacao: "Churrasco, costela, carnes grelhadas, cordeiro.",
    queijos: "Queijos curados: parmesão, gouda.",
    descricao: "Malbec reserva argentino encorpado e estruturado, com fruta madura e boa persistência. Feito para carne vermelha.",
    combina_se_voce_gosta: "de tinto encorpado e marcante para churrasco.",
  },
  {
    id: "peccato-cabernet",
    codigo: "01022",
    foto: "fotos/peccato-cabernet.webp",
    adegas: ["ecopark-iv"],
    nome: "Peccato di Vino Cabernet Sauvignon",
    produtor: "Bodegas Aguirre",
    tipo: "Tinto",
    uva: "Cabernet Sauvignon",
    pais: "Chile",
    regiao: "Valle Central",
    safra: "—",
    alcool: 12.5,
    docura: 0, corpo: 4, taninos: 4, acidez: 3,
    gelavel: false,
    temperatura: "16–18 °C",
    harmonizacao: "Carnes vermelhas, hambúrguer, massas com molho encorpado.",
    queijos: "Queijos fortes: provolone, gorgonzola.",
    descricao: "Cabernet chileno encorpado, com fruta escura e um leve toque de pimentão. Estruturado e cheio de sabor.",
    combina_se_voce_gosta: "de tinto encorpado e marcante.",
  },
  {
    id: "rei-dom-joao-douro",
    codigo: "001002",
    foto: "fotos/rei-dom-joao-douro.png",
    adegas: ["ecopark-iv"],
    nome: "Rei D. João IV DOC Douro",
    produtor: "Caves Campelo",
    tipo: "Tinto",
    uva: "Touriga Nacional · Touriga Franca · Tinta Roriz",
    pais: "Portugal",
    regiao: "Douro",
    safra: "—",
    alcool: 13.5,
    docura: 0, corpo: 4, taninos: 4, acidez: 3,
    gelavel: false,
    temperatura: "16–18 °C",
    harmonizacao: "Carnes assadas, cordeiro, bacalhau, feijoada.",
    queijos: "Queijos curados e intensos.",
    descricao: "Tinto português do Douro, encorpado e elegante, com fruta escura e taninos firmes. Um clássico gastronômico.",
    combina_se_voce_gosta: "de tinto português estruturado e sério.",
  },
  {
    id: "cantarinha-tinto",
    codigo: "5601356025942",
    foto: "fotos/cantarinha-tinto.png",
    adegas: ["ecopark-iv"],
    nome: "Cantarinha Tinto Meio Seco",
    produtor: "Adega de Redondo",
    tipo: "Tinto",
    uva: "Aragonez · Trincadeira",
    pais: "Portugal",
    regiao: "Alentejo",
    safra: "—",
    alcool: 12.5,
    docura: 2, corpo: 3, taninos: 2, acidez: 3,
    gelavel: false,
    temperatura: "16–18 °C",
    harmonizacao: "Petiscos, carnes assadas, pratos do dia a dia.",
    queijos: "Queijos meios-curados.",
    descricao: "Tinto português meio-seco: macio, com um leve toque adocicado que agrada quem está começando. Fácil e versátil.",
    combina_se_voce_gosta: "de tinto suave, macio e sem amargor.",
  },
  {
    id: "peccato-sauvignon-blanc",
    codigo: "00974",
    foto: "fotos/peccato-sauvignon-blanc.png",
    adegas: ["ecopark-iv"],
    nome: "Peccato di Vino Sauvignon Blanc",
    produtor: "Bodegas Aguirre",
    tipo: "Branco",
    uva: "Sauvignon Blanc",
    pais: "Chile",
    regiao: "Valle Central",
    safra: "—",
    alcool: 12.5,
    docura: 0, corpo: 2, taninos: 0, acidez: 5,
    gelavel: true,
    temperatura: "7–9 °C (bem gelado)",
    harmonizacao: "Frutos do mar, ceviche, saladas, comida leve.",
    queijos: "Queijo de cabra, ricota, minas frescal.",
    descricao: "Branco chileno bem seco e cítrico, com acidez refrescante (limão, maracujá). Super gelado, é puro frescor.",
    combina_se_voce_gosta: "de bebida gelada, cítrica e refrescante.",
  },
  {
    id: "peccato-chardonnay",
    codigo: "1059",
    foto: "fotos/peccato-chardonnay.webp",
    adegas: ["ecopark-iv"],
    nome: "Peccato di Vino Chardonnay Seco",
    produtor: "Bodegas Aguirre",
    tipo: "Branco",
    uva: "Chardonnay",
    pais: "Chile",
    regiao: "Valle Central",
    safra: "—",
    alcool: 13,
    docura: 0, corpo: 3, taninos: 0, acidez: 3,
    gelavel: true,
    temperatura: "8–10 °C (bem gelado)",
    harmonizacao: "Peixes, camarão, frango cremoso, massas.",
    queijos: "Queijos amanteigados, brie, gruyère.",
    descricao: "Chardonnay chileno seco, mais encorpado e cremoso, com fruta madura. Cheio de sabor, ótimo bem gelado.",
    combina_se_voce_gosta: "de branco seco mais encorpado e cremoso.",
  },
  {
    id: "tres-medallas-branco",
    codigo: "00562",
    foto: "fotos/tres-medallas-branco.png",
    adegas: ["ecopark-iv"],
    nome: "Tres Medallas Branco",
    produtor: "Santa Rita",
    tipo: "Branco",
    uva: "Sauvignon Blanc",
    pais: "Chile",
    regiao: "Valle Central",
    safra: "—",
    alcool: 12.5,
    docura: 1, corpo: 2, taninos: 0, acidez: 4,
    gelavel: true,
    temperatura: "8–10 °C (bem gelado)",
    harmonizacao: "Peixes, frango, saladas, frutos do mar.",
    queijos: "Queijos frescos e suaves.",
    descricao: "Branco chileno fresco e equilibrado, leve e agradável. Vai muito bem gelado com pratos leves.",
    combina_se_voce_gosta: "de branco leve e fresco.",
  },
  {
    id: "castillo-utrera-branco",
    codigo: "8410261373201",
    foto: "fotos/castillo-utrera-branco.jpg",
    adegas: ["ecopark-iv"],
    nome: "Castillo de Utrera Branco",
    produtor: "Bodegas Ayuso",
    tipo: "Branco",
    uva: "Airén",
    pais: "Espanha",
    regiao: "—",
    safra: "—",
    alcool: 11.5,
    docura: 1, corpo: 2, taninos: 0, acidez: 3,
    gelavel: true,
    temperatura: "8–10 °C (bem gelado)",
    harmonizacao: "Petiscos, saladas, peixes grelhados, frango.",
    queijos: "Queijos frescos e leves.",
    descricao: "Branco espanhol leve e fácil de beber, fresco e descomplicado. Ótimo para o dia a dia, bem gelado no calor.",
    combina_se_voce_gosta: "de um branco leve, gelado e sem complicação.",
  },
  {
    id: "crotta-chenin-ugni",
    codigo: "00056",
    foto: "fotos/crotta-chenin-ugni.jpg",
    adegas: ["ecopark-iv"],
    nome: "Crotta Chenin Ugni Blanc",
    produtor: "Familia Crotta",
    tipo: "Branco",
    uva: "Chenin Blanc · Ugni Blanc",
    pais: "Argentina",
    regiao: "Mendoza",
    safra: "—",
    alcool: 12,
    docura: 1, corpo: 2, taninos: 0, acidez: 4,
    gelavel: true,
    temperatura: "8–10 °C (bem gelado)",
    harmonizacao: "Peixes, frango, saladas, petiscos.",
    queijos: "Queijos frescos e leves.",
    descricao: "Branco argentino leve e fresco, com boa acidez e notas cítricas e florais. Descomplicado e gostoso bem gelado.",
    combina_se_voce_gosta: "de branco leve, fresco e fácil.",
  },
  {
    id: "espumante-lacroix-demi-sec",
    codigo: "00976",
    foto: "fotos/espumante-lacroix-demi-sec.png",
    adegas: ["ecopark-iv"],
    nome: "Espumante Lacroix Demi Sec",
    produtor: "Undurraga",
    tipo: "Espumante",
    uva: "Chardonnay · Pinot Noir",
    pais: "Chile",
    regiao: "Valle Central",
    safra: "—",
    alcool: 11,
    docura: 3, corpo: 1, taninos: 0, acidez: 3,
    gelavel: true,
    temperatura: "6–8 °C (bem gelado)",
    harmonizacao: "Sobremesas, frutas, petiscos, brindes.",
    queijos: "Queijos suaves; ótimo com doces.",
    descricao: "Espumante meio-doce (demi sec), leve e com borbulhas macias. Agrada quem gosta de um docinho e é perfeito para brindar.",
    combina_se_voce_gosta: "de espumante levemente adocicado e fácil.",
  },
  {
    id: "rose-city-noble",
    codigo: "00055",
    foto: "fotos/rose-city-noble.png",
    adegas: ["ecopark-iv"],
    nome: "Rosé City Noble",
    produtor: "Bodegas Aguirre",
    tipo: "Rosé",
    uva: "Syrah",
    pais: "Chile",
    regiao: "Valle Central",
    safra: "—",
    alcool: 11.5,
    docura: 1, corpo: 1, taninos: 0, acidez: 4,
    gelavel: true,
    temperatura: "7–9 °C (bem gelado)",
    harmonizacao: "Petiscos, saladas, comida leve, dia de piscina.",
    queijos: "Queijos frescos e leves.",
    descricao: "Rosé leve e refrescante, delicado e fácil de agradar. O clássico da taça gelada num dia quente.",
    combina_se_voce_gosta: "de algo leve, gelado e descomplicado.",
  },
  {
    id: "peccato-rose",
    codigo: "00979",
    foto: "fotos/peccato-rose.png",
    adegas: ["ecopark-iv"],
    nome: "Peccato di Vino Rosé",
    produtor: "Bodegas Aguirre",
    tipo: "Rosé",
    uva: "Cabernet Sauvignon",
    pais: "Chile",
    regiao: "Valle Central",
    safra: "—",
    alcool: 12,
    docura: 1, corpo: 1, taninos: 0, acidez: 4,
    gelavel: true,
    temperatura: "7–9 °C (bem gelado)",
    harmonizacao: "Petiscos, saladas, comida japonesa, massas leves.",
    queijos: "Queijos frescos e leves.",
    descricao: "Rosé chileno leve e seco, frutado e refrescante. Combina com quase tudo e cai muito bem no calor.",
    combina_se_voce_gosta: "de um rosé leve e refrescante.",
  },
  {
    id: "crotta-rosado",
    codigo: "2001",
    foto: "fotos/crotta-rosado.png",
    adegas: ["ecopark-iv"],
    nome: "Crotta Rosado Seco",
    produtor: "Familia Crotta",
    tipo: "Rosé",
    uva: "Malbec",
    pais: "Argentina",
    regiao: "Mendoza",
    safra: "—",
    alcool: 12.5,
    docura: 0, corpo: 1, taninos: 0, acidez: 4,
    gelavel: true,
    temperatura: "7–9 °C (bem gelado)",
    harmonizacao: "Petiscos, saladas, carnes brancas, comida leve.",
    queijos: "Queijos frescos e leves.",
    descricao: "Rosé argentino seco, feito de uvas tintas, com fruta vermelha delicada. Leve e refrescante bem gelado.",
    combina_se_voce_gosta: "de rosé seco e frutado.",
  },
  {
    id: "errante-rosado",
    codigo: "7798370260171",
    foto: "fotos/errante-rosado.webp",
    adegas: ["ecopark-iv"],
    nome: "Errante Rosado",
    produtor: "Salvador Patti",
    tipo: "Rosé",
    uva: "Criolla",
    pais: "Argentina",
    regiao: "Mendoza",
    safra: "—",
    alcool: 12.5,
    docura: 1, corpo: 1, taninos: 0, acidez: 4,
    gelavel: true,
    temperatura: "7–9 °C (bem gelado)",
    harmonizacao: "Petiscos, saladas, massas leves, dia de piscina.",
    queijos: "Queijos frescos e leves.",
    descricao: "Rosé argentino jovem e frutado, leve e fácil de beber. Pede taça gelada e clima descontraído.",
    combina_se_voce_gosta: "de algo leve, frutado e gelado.",
  },
];
