/*
 * ============================================================================
 *  VINHO 24 HORAS — Base de dados dos vinhos
 * ============================================================================
 *
 *  Este arquivo é a "planilha" do protótipo. Cada objeto abaixo é UMA LINHA
 *  da futura planilha do Google Sheets. As chaves (nome, tipo, docura...) são
 *  as COLUNAS. Quando formos migrar para o Google Sheets, basta o site ler a
 *  planilha e montar exatamente esses mesmos objetos — nada mais muda.
 *
 *  ESCALAS (de 0 a 5) — pensadas para o público brasileiro iniciante:
 *    docura   0 = bem seco   ......... 5 = bem doce
 *    corpo    0 = leve/fácil ......... 5 = encorpado/potente
 *    taninos  0 = macio      ......... 5 = marcante (aquele "amarra a boca")
 *    acidez   0 = baixa      ......... 5 = alta/refrescante
 *
 *  Dica: "gelavel: true" marca vinhos gostosos BEM GELADOS — ótimo argumento
 *  para o clima tropical e para quem está acostumado com cerveja gelada.
 *
 *  FOTO: o campo "foto" é opcional. Se você colocar o link de uma imagem
 *  (ex: foto: "fotos/malbec.jpg"), o app mostra a foto real da garrafa.
 *  Se deixar vazio ("") ou não colocar, o app desenha uma garrafa ilustrada
 *  automaticamente na cor do tipo do vinho.
 * ============================================================================
 */

// As duas adegas. O QR de cada porta aponta para ?adega=<slug>
const ADEGAS = {
  "unidade-centro": {
    nome: "Vinho 24 Horas · Unidade Centro",
    cidade: "São Paulo",
  },
  "unidade-praia": {
    nome: "Vinho 24 Horas · Unidade Praia",
    cidade: "Litoral",
  },
};

const VINHOS = [
  {
    id: "malbec-classico",
    foto: "", // ex: "fotos/malbec.jpg" — deixe "" para usar a garrafa ilustrada
    adegas: ["unidade-centro", "unidade-praia"],
    nome: "Malbec Reserva",
    produtor: "Bodega Los Andes",
    tipo: "Tinto",
    uva: "Malbec",
    pais: "Argentina",
    regiao: "Mendoza",
    safra: 2021,
    alcool: 14,
    docura: 1,
    corpo: 4,
    taninos: 4,
    acidez: 2,
    gelavel: false,
    temperatura: "16–18 °C",
    harmonizacao: "Carnes vermelhas grelhadas, churrasco, hambúrguer artesanal.",
    queijos: "Queijos curados: parmesão, gouda envelhecido.",
    descricao:
      "O tinto mais 'coringa' para quem gosta de carne. Encorpado, frutado (ameixa, amora) e macio o suficiente para agradar quem está começando.",
    combina_se_voce_gosta: "de vinho tinto encorpado e churrasco.",
  },
  {
    id: "cabernet-sauvignon",
    adegas: ["unidade-centro"],
    nome: "Cabernet Sauvignon Gran Reserva",
    produtor: "Viña del Valle",
    tipo: "Tinto",
    uva: "Cabernet Sauvignon",
    pais: "Chile",
    regiao: "Valle del Maipo",
    safra: 2020,
    alcool: 13.5,
    docura: 0,
    corpo: 5,
    taninos: 5,
    acidez: 3,
    gelavel: false,
    temperatura: "17–19 °C",
    harmonizacao: "Costela, cordeiro, massas com molho encorpado.",
    queijos: "Queijos fortes: gorgonzola, provolone.",
    descricao:
      "Um tinto sério, para quem já curte estrutura e aquele tanino que 'amarra' a boca. Aromas de pimentão, cassis e um toque de madeira.",
    combina_se_voce_gosta: "de vinhos potentes e marcantes.",
  },
  {
    id: "pinot-noir",
    adegas: ["unidade-centro", "unidade-praia"],
    nome: "Pinot Noir",
    produtor: "Maison du Sud",
    tipo: "Tinto",
    uva: "Pinot Noir",
    pais: "França",
    regiao: "Languedoc",
    safra: 2022,
    alcool: 12.5,
    docura: 1,
    corpo: 2,
    taninos: 2,
    acidez: 3,
    gelavel: true,
    temperatura: "14–16 °C (leve gelada)",
    harmonizacao: "Salmão, frango, risoto de cogumelos, tábua de frios.",
    queijos: "Brie, camembert, queijos leves.",
    descricao:
      "Tinto leve e elegante que pode ir levemente gelado — perfeito para o calor. Delicado, frutado (cereja, framboesa) e fácil de beber.",
    combina_se_voce_gosta: "de tinto leve, sem aquele amargor forte.",
  },
  {
    id: "chardonnay",
    adegas: ["unidade-centro", "unidade-praia"],
    nome: "Chardonnay",
    produtor: "Estância do Sol",
    tipo: "Branco",
    uva: "Chardonnay",
    pais: "Brasil",
    regiao: "Serra Gaúcha",
    safra: 2023,
    alcool: 12.5,
    docura: 1,
    corpo: 3,
    taninos: 0,
    acidez: 3,
    gelavel: true,
    temperatura: "8–10 °C (bem gelado)",
    harmonizacao: "Peixes, camarão, frango cremoso, moqueca.",
    queijos: "Queijos amanteigados, brie, gruyère.",
    descricao:
      "Branco encorpado e cremoso, com notas de fruta madura e um toque amanteigado. Servido bem gelado, é uma delícia no calor.",
    combina_se_voce_gosta: "de branco mais 'cheio', não muito ácido.",
  },
  {
    id: "sauvignon-blanc",
    adegas: ["unidade-praia"],
    nome: "Sauvignon Blanc",
    produtor: "Viña del Valle",
    tipo: "Branco",
    uva: "Sauvignon Blanc",
    pais: "Chile",
    regiao: "Valle de Casablanca",
    safra: 2023,
    alcool: 12,
    docura: 0,
    corpo: 2,
    taninos: 0,
    acidez: 5,
    gelavel: true,
    temperatura: "7–9 °C (bem gelado)",
    harmonizacao: "Frutos do mar, ceviche, saladas, comida leve.",
    queijos: "Queijo de cabra, ricota, minas frescal.",
    descricao:
      "Branco super refrescante e cítrico (limão, maracujá). O 'chopp' dos vinhos brancos: leve, ácido e pede gelo no clima quente.",
    combina_se_voce_gosta: "de bebida gelada, cítrica e refrescante.",
  },
  {
    id: "rose-provence",
    adegas: ["unidade-centro", "unidade-praia"],
    nome: "Rosé Provence",
    produtor: "Maison du Sud",
    tipo: "Rosé",
    uva: "Grenache · Cinsault",
    pais: "França",
    regiao: "Provence",
    safra: 2023,
    alcool: 12.5,
    docura: 1,
    corpo: 1,
    taninos: 0,
    acidez: 4,
    gelavel: true,
    temperatura: "7–9 °C (bem gelado)",
    harmonizacao: "Petiscos, saladas, comida japonesa, dia de piscina.",
    queijos: "Queijos frescos e leves.",
    descricao:
      "Leve, seco e delicado, com cor de pêssego. O vinho 'praia e piscina' por excelência — refrescante e fácil de agradar todo mundo.",
    combina_se_voce_gosta: "de algo leve, gelado e descomplicado.",
  },
  {
    id: "prosecco",
    adegas: ["unidade-centro", "unidade-praia"],
    nome: "Prosecco Brut",
    produtor: "Cantina Veneto",
    tipo: "Espumante",
    uva: "Glera",
    pais: "Itália",
    regiao: "Veneto",
    safra: 2023,
    alcool: 11,
    docura: 2,
    corpo: 1,
    taninos: 0,
    acidez: 4,
    gelavel: true,
    temperatura: "6–8 °C (bem gelado)",
    harmonizacao: "Aperitivos, frituras, comida japonesa, brinde.",
    queijos: "Queijos frescos, mozzarella de búfala.",
    descricao:
      "Espumante italiano de borbulha fina, levemente frutado e fácil. Perfeito para brindar ou simplesmente refrescar num dia quente.",
    combina_se_voce_gosta: "de bolhas, leveza e um docinho de leve.",
  },
  {
    id: "espumante-moscatel",
    adegas: ["unidade-centro"],
    nome: "Moscatel Espumante",
    produtor: "Estância do Sol",
    tipo: "Espumante",
    uva: "Moscato",
    pais: "Brasil",
    regiao: "Serra Gaúcha",
    safra: 2023,
    alcool: 8,
    docura: 5,
    corpo: 1,
    taninos: 0,
    acidez: 3,
    gelavel: true,
    temperatura: "6–8 °C (bem gelado)",
    harmonizacao: "Sobremesas, frutas, panetone, torta de limão.",
    queijos: "Queijos azuis (contraste doce + salgado).",
    descricao:
      "Doce, aromático (uva, pêssego, mel) e com pouco álcool. O queridinho de quem 'não gosta de vinho' — porta de entrada perfeita.",
    combina_se_voce_gosta: "de bebida doce e suave, sem amargor.",
  },
  {
    id: "carmenere",
    adegas: ["unidade-praia"],
    nome: "Carménère",
    produtor: "Viña del Valle",
    tipo: "Tinto",
    uva: "Carménère",
    pais: "Chile",
    regiao: "Valle de Colchagua",
    safra: 2021,
    alcool: 13.5,
    docura: 1,
    corpo: 4,
    taninos: 3,
    acidez: 2,
    gelavel: false,
    temperatura: "16–18 °C",
    harmonizacao: "Feijoada, carnes assadas, comida apimentada.",
    queijos: "Queijos curados e defumados.",
    descricao:
      "A uva símbolo do Chile: encorpada, com notas de pimenta, chocolate e fruta escura. Macia e cheia de sabor.",
    combina_se_voce_gosta: "de tinto encorpado, mas macio e frutado.",
  },
  {
    id: "vinho-verde",
    adegas: ["unidade-praia", "unidade-centro"],
    nome: "Vinho Verde",
    produtor: "Quinta do Minho",
    tipo: "Branco",
    uva: "Loureiro · Alvarinho",
    pais: "Portugal",
    regiao: "Minho",
    safra: 2023,
    alcool: 10.5,
    docura: 1,
    corpo: 1,
    taninos: 0,
    acidez: 4,
    gelavel: true,
    temperatura: "7–9 °C (bem gelado)",
    harmonizacao: "Petiscos, bacalhau, frutos do mar, dia de calor.",
    queijos: "Queijos frescos e leves.",
    descricao:
      "Português leve, com uma leve agulha (borbulha sutil) e baixo álcool. Ultra refrescante — pede sol, praia e gelo.",
    combina_se_voce_gosta: "de algo bem leve, refrescante e fácil.",
  },
  {
    id: "tempranillo",
    adegas: ["unidade-centro"],
    nome: "Tempranillo Crianza",
    produtor: "Bodega Ribera",
    tipo: "Tinto",
    uva: "Tempranillo",
    pais: "Espanha",
    regiao: "Rioja",
    safra: 2020,
    alcool: 14,
    docura: 0,
    corpo: 4,
    taninos: 3,
    acidez: 3,
    gelavel: false,
    temperatura: "16–18 °C",
    harmonizacao: "Paella, embutidos, carnes assadas, cordeiro.",
    queijos: "Manchego, queijos curados.",
    descricao:
      "Clássico espanhol com passagem por barrica: fruta vermelha, baunilha e um toque de couro. Equilibrado e gastronômico.",
    combina_se_voce_gosta: "de tinto clássico com boa estrutura.",
  },
  {
    id: "riesling",
    adegas: ["unidade-praia"],
    nome: "Riesling",
    produtor: "Weingut Rhein",
    tipo: "Branco",
    uva: "Riesling",
    pais: "Alemanha",
    regiao: "Mosel",
    safra: 2022,
    alcool: 11,
    docura: 3,
    corpo: 2,
    taninos: 0,
    acidez: 4,
    gelavel: true,
    temperatura: "8–10 °C (bem gelado)",
    harmonizacao: "Comida tailandesa/apimentada, frutos do mar, curry.",
    queijos: "Queijos suaves e frescos.",
    descricao:
      "Branco levemente adocicado e muito aromático, com acidez que equilibra. Ótimo para pratos apimentados e para quem gosta de um docinho.",
    combina_se_voce_gosta: "de branco meio-doce, aromático e gelado.",
  },
];
